oem/exam/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    #url(r'^out/', views.logout_page),
    url(r'^(?P<test_id>[0-9]+)/$', views.give_test, name='test'),
]

oem/oem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy
from django.conf import settings
from authentication.views import logout_page
from django.contrib.auth.views import login
from django.conf.urls.static import static
# from .views import course_graph_view
from . import views

admin.site.site_header = ugettext_lazy('Obejctive Exam Management')
admin.site.site_title = ugettext_lazy('Obejctive Exam Management')

urlpatterns = [
    url(r'^$', views.main_view),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^logout/', logout_page, name='logout'),
    url(r'^login/', login, name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^test/', include('exam.urls', namespace='exam')),
    url(r'^report/$', views.faculty_view, name='facultyreports'),
    url(r'^graph/student/(?P<course_id>[0-9]+)/$', views.student_course_graph_view, name='studentgraph'),
    url(r'^graph/(?P<student_id>[0-9]+)/(?P<course_id>[0-9]+)/$', views.student_faculty_course_graph_view, name='studentfacultygraph'),
    # url(r'^graph/course/(?P<course_id>[0-9]+)/$', course_graph_view, name='facultycoursegraph'),
    url(r'^faculty/test/(?P<test_id>[0-9]+)/$', views.faculty_test_view, name='facultytest'),
    url(r'^course/(?P<course_id>[0-9]+)/$', views.faculty_course_view, name='facultycourse'),



] + static(settings.STATIC_URL)

oem/templates/Unauthorized.html
Unauthorized

oem/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Objective Exam Management</title>

    {% block head %}
    {% include 'material/includes/material_css.html' %}

    <style type="text/css">
      html, body {
          background: #eee;
          height: 100%;
      }
    </style>
    {% block extrahead %}{% endblock %}
    {% endblock %}
  </head>
  <body class="valign-wrapper2">
      {% block sidebar %}{% endblock %}
      <div class="{% block container_class %}container expand-on-small-only{% endblock %}">
          {% block content %}{% endblock %}
      </div>
      {% block js %}
      <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      {% include 'material/includes/material_js.html' %}
      {% block extrajs %}{% endblock %}
      {% endblock %}
  </body>
</html>

oem/templates/base_form.html
{% extends 'material/frontend/base_module.html' %}

{% block extrahead %}
<style type="text/css">
  @media only screen and (min-width : 601px) {
      #id_card_type_container {
          margin-top: 40px;
          margin-left: 50px;
      }
}
</style>
{% endblock %}

{% block content %}
<div class="row valign change-form">
    <div class="{% block formclass %}col s12 m8 offset-m2 l8 offset-l2{% endblock %}">
        <div class="card">
            <form method="POST" enctype="multipart/form-data">
                <div class="card-content">
                    <span class="card-title grey-text text-darken-2">{% block formtitle %}Form{% endblock %}</span>
                    {% csrf_token %}
                    {% block formbody %}{% endblock %}
                </div>
                <div class="card-action">
                    {% block actions %}
                    <div class="right-align">
                        {% block formbuttons %}<button class="btn btn-primary" type="submit">Submit</button>{% endblock %}
                    </div>
                    {% endblock %}
                </div>
            </form>
        </div>
    </div>
</div>
{% block result %}
{% endblock %}
{% endblock %}

oem/templates/faculty_course_view.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ course.name }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12  m6">
        <div class="card">
            <div class="card-content">
                <h4> Graph of average marks</h4>
                <div style="width:100%" onready="makeGraph()">
                    <div>
                        <canvas id="canvas" ></canvas>
                    </div>
                </div>
                <script>

                    var lineChartData = {
                        labels : [{% for testname,result in data %} "{{ testname }}", {% endfor %}],
                        datasets : [
                            {
                                label: "My First dataset",
                                fillColor : "rgba(220,220,220,0.2)",
                                strokeColor : "rgba(220,220,220,1)",
                                pointColor : "rgba(220,220,220,1)",
                                pointStrokeColor : "#fff",
                                pointHighlightFill : "#fff",
                                pointHighlightStroke : "rgba(220,220,220,1)",
                                data : [{% for testname,result in data %} {{ result }}, {% endfor %}]
                            },

                        ]
                    }

                    var ctx = document.getElementById("canvas").getContext("2d");
                    window.myLine = new Chart(ctx).Line(lineChartData, {
                        responsive: true
                    });

                </script>
            </table>
            </div>
        </div>
    </div>
    <div class="col s12  m6">
        <div class="card">
            <div class="card-content">
                <h4> Tests </h4>
            <table>
                {% for test in tests %}
                <tr>
                <td><a href="{% url 'facultytest' test.pk %}">{{ test.name }}</a></td>
                <td><a href="{% url 'facultycourse' test.course.pk %}">{{ test.course.name }}</a></td>
                <td>{{ test.start_time }}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col s12  m12">
        <div class="card">
            <div class="card-content">
                <h4> Students </h4>
                <table>
                <tr>
                    <th>Student Name</th>
                    {% for test in tests %}
                    <th>{{ test.name }}</th>
                    {% endfor %}
                </tr>
                {% for student, mark_list in marks %}

                    <tr>
                    <td><a href="{% url 'studentfacultygraph' student_id=student.pk course_id=mark_list.0.0.course.pk %}">{{ student.username }}</a></td>
                    {% for test,marks in mark_list %}
                        <td>{{ marks }}</td>
                    {% endfor %}

                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oem/templates/faculty_dashboard.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ "Dashboard" }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 offset-m1 m5">
        <a href="{% url 'facultyreports' %}">
            <div class="card">
                <div class="card-content">
                    <center>
                        <br><br>
                        <h3>Reports</h3>
                        <br><br>
                    </center>
                </div>
            </div>
        </a>
    </div>
    <div class="col s12 m5">
        <a href="{% url 'admin:index' %}">
            <div class="card">
                <div class="card-content">
                    <center>
                        <br><br>
                        <h3>Tests</h3>
                        <br><br>
                    </center>
                </div>
            </div>
        </a>
    </div>
</div>
{% endblock %}

oem/templates/faculty_test_view.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ test.name }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 offset-m3 m6">
        <div class="card">
            <div class="card-content">
                <h4> Students</h4>
                <table>
                <tr>
                    <th>Name</th>
                    <th>Marks</th>
                </tr>
                {% for student, mark in marks %}
                    <tr>
                    <td>{{ student }}</td>
                    <td>{{ mark }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oem/templates/faculty_view.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ "Dashboard" }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 offset-m3 m6">
        <div class="card">
            <div class="card-content">
                <h4> Courses </h4>
                <table>
                {% for course in faculty_courses %}
                    <tr>
                    <td><a href="{% url 'facultycourse' course.pk %}">{{ course.name }}</a></td>
                    <td>{{ course.pk }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oem/templates/lineChart.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ course.name }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 offset-m2 m8">
        <div class="card">
            <div class="card-content">
                <div style="width:100%">
                    <div>
                        <canvas id="canvas" ></canvas>
                    </div>
                </div>
                <script>

                    var lineChartData = {
                        labels : [{% for testname,result in data %} "{{ testname }}", {% endfor %}],
                        datasets : [
                            {
                                label: "My First dataset",
                                fillColor : "rgba(220,220,220,0.2)",
                                strokeColor : "rgba(220,220,220,1)",
                                pointColor : "rgba(220,220,220,1)",
                                pointStrokeColor : "#fff",
                                pointHighlightFill : "#fff",
                                pointHighlightStroke : "rgba(220,220,220,1)",
                                data : [{% for testname,result in data %} {{ result }}, {% endfor %}]
                            },

                        ]
                    }

                    var ctx = document.getElementById("canvas").getContext("2d");
                    window.myLine = new Chart(ctx).Line(lineChartData, {
                        responsive: true
                    });

                </script>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oem/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
<form action="login" method="post">
{% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit"/>
</form>
</body>
</html>

oem/templates/student_view.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ "Dashboard" }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12  m6">
        <div class="card">
            <div class="card-content">
                <h4> Courses </h4>
                <table>
                {% for course in student_courses %}
                    <tr>
                    <td><a href="{% url 'studentgraph' course.pk %}">{{ course.name }}</a></td>
                    <td>{{ course.pk }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="col s12  m6">
        <div class="card">
            <div class="card-content">
                <h4> Tests </h4>
            <table>
                {% for test, result in student_test_result %}
                <tr>
                <td><a href="{% url 'exam:test' test.pk %}">{{ test.name }} - {{ test.course.name }}</a></td>
                <td>{{ result }}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

oem/templates/test.html
{% extends 'base_form.html' %}
{% load material_form %}
{% block page_title %}<a href="/">{{ form.title }}</a>{% endblock %}
{% block extrahead %}
<style type="text/css">
    {{ form.css }}
</style>

{% endblock %}

{% block formclass %}{{ form.blockclass|default:"col s12 m8 offset-m2 l8 offset-l2" }}{% endblock %}

{% block formtitle %}{{ "" }}{% endblock %}

{% block formbody %}

<span id="clockdiv" style="float: right;">
	<span>
		<span id="days"></span>
		<span class="smalltext"> Days </span>

		<span id="hours"></span>
		<span class="smalltext">:</span>
	</span>
	<span>
		<span id="minutes"></span>
		<span class="smalltext">:</span>
	</span>
	<span>
		<span id="seconds"></span>
		<span class="smalltext"></span>
	</span>
</span>

<script type="text/javascript">
	function getTimeRemaining(endtime)
	{

		var t = Date.parse(endtime) - Date.parse(new Date());
		var seconds = Math.floor((t / 1000) % 60);
		var minutes = Math.floor((t / 1000 / 60) % 60);
		var hours = Math.floor((t / (1000 * 60 * 60)) % 24);
		var days = Math.floor(t / (1000 * 60 * 60 * 24));

		var ret = {total:t, days:days, hours:hours, minutes:minutes, seconds:seconds};
		return ret;
	}

	function initializeClock(id, endtime)
	{
		var clock = document.getElementById(id);
		var daysSpan = clock.querySelector('#days');
		var hoursSpan = clock.querySelector('#hours');
		var minutesSpan = clock.querySelector('#minutes');
		var secondsSpan = clock.querySelector('#seconds');

		function updateClock()
		{
			var t = getTimeRemaining(endtime);
			daysSpan.innerHTML = t.days;
            if(t.days==0) {
                daysSpan.style.visibility = False
            }
			hoursSpan.innerHTML = ('0' + t.hours).slice(-2);
			minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);
			secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);

			if (t.total <= 0)
			{
				clearInterval(timeinterval);
			}
		}

		updateClock();
		var timeinterval = setInterval(updateClock, 1000);
	}

	var deadline = new Date(Date.parse(new Date()) + {{duration}});
	initializeClock('clockdiv', deadline);

</script>
        {% form form=form %}{% endform %}

{% endblock %}


{#{% extends "material/frontend/base_module.html" %}#}
{#{% load i18n material_form %}#}

{#{% block content %}#}
{#<div class="row">#}
{#    <div class="col s12 offset-m1 m10">#}
{#        <div class="card">#}
{#            <div class="card-content">#}
{#                <span class="card-title black-text"></span>#}
{#                 <span id="clockdiv" style="float: right;">#}
{#	<span>#}
{#		<span id="days"></span>#}
{#		<span class="smalltext"> Days </span>#}
{##}
{#		<span id="hours"></span>#}
{#		<span class="smalltext">:</span>#}
{#	</span>#}
{#	<span>#}
{#		<span id="minutes"></span>#}
{#		<span class="smalltext">:</span>#}
{#	</span>#}
{#	<span>#}
{#		<span id="seconds"></span>#}
{#		<span class="smalltext"></span>#}
{#	</span>#}
{#</span>#}
{##}
{#<script type="text/javascript">#}
{#	function getTimeRemaining(endtime)#}
{#	{#}
{##}
{#		var t = Date.parse(endtime) - Date.parse(new Date());#}
{#		var seconds = Math.floor((t / 1000) % 60);#}
{#		var minutes = Math.floor((t / 1000 / 60) % 60);#}
{#		var hours = Math.floor((t / (1000 * 60 * 60)) % 24);#}
{#		var days = Math.floor(t / (1000 * 60 * 60 * 24));#}
{##}
{#		var ret = {total:t, days:days, hours:hours, minutes:minutes, seconds:seconds};#}
{#		return ret;#}
{#	}#}
{##}
{#	function initializeClock(id, endtime)#}
{#	{#}
{#		var clock = document.getElementById(id);#}
{#		var daysSpan = clock.querySelector('#days');#}
{#		var hoursSpan = clock.querySelector('#hours');#}
{#		var minutesSpan = clock.querySelector('#minutes');#}
{#		var secondsSpan = clock.querySelector('#seconds');#}
{##}
{#		function updateClock()#}
{#		{#}
{#			var t = getTimeRemaining(endtime);#}
{#			daysSpan.innerHTML = t.days;#}
{#            if(t.days==0) {#}
{#                daysSpan.style.visibility = False#}
{#            }#}
{#			hoursSpan.innerHTML = ('0' + t.hours).slice(-2);#}
{#			minutesSpan.innerHTML = ('0' + t.minutes).slice(-2);#}
{#			secondsSpan.innerHTML = ('0' + t.seconds).slice(-2);#}
{##}
{#			if (t.total <= 0)#}
{#			{#}
{#				clearInterval(timeinterval);#}
{#			}#}
{#		}#}
{##}
{#		updateClock();#}
{#		var timeinterval = setInterval(updateClock, 1000);#}
{#	}#}
{##}
{#	var deadline = new Date(Date.parse(new Date()) + {{duration}});#}
{#	initializeClock('clockdiv', deadline);#}
{##}
{#</script>#}
{#        {% form form=form %}{% endform %}#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}

oem/templates/test_submit.html
{% extends "material/frontend/base_module.html" %}
{% load i18n material_form %}
{% block page_title %}<a href="/">{{ title }}</a>{% endblock %}
{% block content %}
<div class="row">
    <div class="col s12 offset-m3 m6">
        <div class="card">
            <div class="card-content">
                <center>{% if not submitted %}
                    <h4>Test Successfully Submitted</h4>
                    <br>
                    <p>
                        You got <b>{{correct_count}}</b> questions correct and your final score is <b>{{marks}}</b>
                    </p>{% else %}
                    <h4>You are not allowed to give the test</h4>
                    {% endif %}
                </center>
            </div>
        </div>
    </div>
</div>
{% endblock %}